### ISSUE TITLE
[BoldBLE] Timed out while waiting for Bluetooth to turn on

### ISSUE THREAD

**Issue by iantait** [robbertkl/homebridge-bold-ble#2]
**Describe Your Problem:**

Plugin seems to install OK on macos sonoma, but looking through homebridge logs I see the below.
any ideas how I might debug that?

**Logs:**

```
[BoldBLE] Timed out while waiting for Bluetooth to turn on
```

**Plugin Config:**

```json
        {
            "name": "BoldBLE",
            "accessToken": "xxxxx",
            "refreshToken": "xxxxxx",
            "legacyAuthentication": false,
            "platform": "BoldBLE"
        }
```

**Screenshots:**

**Environment:**

* **Plugin Version**:  1.2.0
* **Homebridge Version**:  v1.7.0  
* **Node.js Version**: v20.9.0 
* **NPM Version**: 10.1.0 
* **Operating System**: macos sonoma

**Comment by robbertkl** [comment]
Hi, I've initially developed this plugin on macOS as well, although an earlier version. I did not have any issues.

I would suggest to try to see if you can get some of the `noble` examples up & running, as somehow it seems it's not even getting BT up & running.

**Comment by iantait** [comment]
Just revisited this - I granted bluetooth permissions to node in system settings -> privacy and now works perfectly.
